/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Second.glb 
*/
import { convertMaterialsToBasic } from '../../util/ConvertMaterial'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function RoomSecond(props) {
  const { nodes, materials } = useGLTF('/models/Second.glb')
  const newMaterial = convertMaterialsToBasic(materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Second_Baked.geometry}
        material={newMaterial.actual_second_bro_Baked}
        position={[26.719, 1.498, 1.614]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/models/Second.glb')
