/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Third.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../../util/ConvertMaterial'
export default function RoomThird(props) {
  const { nodes, materials } = useGLTF('/models/Third.glb')
  const newMaterial = convertMaterialsToBasic(materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Third_Baked.geometry} material={newMaterial.REAL_third_Baked} position={[24.79, -0.201, 0.173]} />
    </group>
  )
}

useGLTF.preload('/models/Third.glb')
